local base = assert(arg[0]:match("^(.*)/tests/[^/]+$"))
local diff = dofile(base .. "/diff.lua")
local checks = 0
local function check(ok, label) assert(ok, label); checks = checks + 1; print("PASS " .. label) end
local function rejects(a, b, patch, needle)
  local ok, err = pcall(diff.build, a, b, patch)
  return not ok and tostring(err):find(needle, 1, true)
end
local d = diff.build("a\nb\nc\n", "a\nx\ny\nc\n", "@@ -2 +2,2 @@\n-b\n+x\n+y\n")
check(#d.rows == 4 and d.rows[2][1] == 2 and d.rows[2][2] == 2 and d.rows[3][1] == nil and d.rows[3][2] == 3, "replace/add aligns gaps without fabricated source lines")
check(d.maps[1][3] == 4 and d.maps[2][4] == 4 and d.changes[1] == 2, "source maps and change destinations")
d = diff.build("a\nb\nc\n", "a\nc\n", "@@ -2 +1,0 @@\n-b\n")
check(d.rows[2][1] == 2 and d.rows[2][2] == nil and d.rows[3][2] == 2, "deletion has correct right-side gap")
d = diff.build("", "\nhi\n", "@@ -0,0 +1,2 @@\n+\n+hi\n")
check(#d.lines[1] == 0 and #d.lines[2] == 2 and #d.rows == 2 and not d.rows[1][1], "empty-to-new preserves blank line and EOF line counts")
d = diff.build("last", "last\n", "@@ -1 +1 @@\n-last\n\\ No newline at end of file\n+last\n")
check(d.original == "last" and #d.lines[1] == 1 and #d.lines[2] == 1, "no-final-newline-only edit preserves source bytes")
d = diff.build("á\r\n\r\nx", "β\r\n\r\nx", "@@ -1 +1 @@\n-á\r\n+β\r\n")
check(d.lines[1][2] == "\r\n" and d.lines[2][3] == "x", "UTF-8 CRLF blank lines and final fragment preserved")
d = diff.build("a\nb\n", "a\r\nx\r\n", "@@ -2 +2 @@\n-b\n+x\n")
check(d.modified == "a\r\nx\r\n", "Git CRLF normalization maps to exact disk bytes")
check(#diff.build("", "", "").rows == 0, "zero-byte files do not invent line one")
check(#diff.build("same\n", "same\n", "diff --git a/a b/b\nsimilarity index 100%\nrename from a\nrename to b\n").rows == 1, "metadata-only rename retains full content")
check(rejects("old\n", "other\n", "", "Sources differ"), "uncovered changed source rejected")
check(rejects("a\n", "b\n", "@@ -1 +1 @@\n-wrong\n+b\n", "Original source"), "stale original payload rejected")
check(rejects("a\n", "b\n", "@@ -1 +1 @@\n-a\n+wrong\n", "Modified source"), "stale modified payload rejected")
check(rejects("a\n", "b\n", "@@ -1,2 +1 @@\n-a\n+b\n", "Incomplete"), "truncated hunk rejected")
check(rejects("", "a\0", "", "Binary"), "NUL source explicitly unsupported")
check(rejects("", "", "Binary files a/a and b/a differ\n", "Binary"), "Git attribute-marked binary explicitly unsupported")
check(rejects("", "", "@@@ -1 -1 +1 @@@\n", "Combined merge"), "combined merge explicitly unsupported")
check(rejects("", "", "index abc..def 160000\n", "Submodule"), "gitlink explicitly unsupported")
check(rejects("", string.rep("a", diff.MAX_BYTES + 1), "", "2 MiB"), "byte cap explicit, no partial success")
check(rejects("", string.rep("\n", diff.MAX_LINES + 1), "", "50,000"), "line cap explicit")
check(rejects("", string.rep("a", diff.MAX_LINE + 1), "", "16 KiB"), "long-line cap bounds tokenizer work")
check(rejects("", "\255", "", "Non-UTF-8"), "invalid UTF-8 encoding explicitly unsupported")
check(#diff.lines("😀\n") == 1 and not pcall(diff.lines, "\237\160\128"), "valid four-byte UTF-8 accepted, surrogate encoding rejected")
check(#diff.build("", "Binary files\n@@@\nSubproject commit abc\nnew file mode 160000\n", "@@ -0,0 +1,4 @@\n+Binary files\n+@@@\n+Subproject commit abc\n+new file mode 160000\n").rows == 4, "source text resembling Git metadata is not misclassified")
local big = string.rep("unchanged\n", diff.MAX_LINES)
local started = os.clock()
d = diff.build(big, big, "")
check(#d.rows == diff.MAX_LINES and d.rows[#d.rows][2] == diff.MAX_LINES and os.clock() - started < 2, "50,000-line mapping is complete and linear/bounded")
d = diff.build("a\nb\nc\nd\ne\n", "a\nB\nc\nd\nE\n", "@@ -2 +2 @@\n-b\n+B\n@@ -5 +5 @@\n-e\n+E\n")
check(diff.revert(d, 1) == "a\nb\nc\nd\nE\n" and diff.revert(d, 2) == "a\nB\nc\nd\ne\n", "reconstruct one exact block while preserving neighbor")
check(d.hunks[1].a == 2 and d.hunks[2].row == 5 and d.hunks[1].height == 1, "hunks retain source ranges and visible block boundaries")
d = diff.build("a\nb", "new\na\nb", "@@ -0,0 +1 @@\n+new\n")
check(diff.revert(d, 1) == "a\nb", "remove added first block without adding EOF newline")
d = diff.build("a\nb", "a\n", "@@ -2 +1,0 @@\n-b\n\\ No newline at end of file\n")
check(diff.revert(d, 1) == "a\nb", "restore deleted EOF fragment exactly")
d = diff.build("é\r\nold\r\n", "é\r\nβ\r\n", "@@ -2 +2 @@\n-old\r\n+β\r\n")
check(diff.revert(d, 1) == "é\r\nold\r\n", "reconstruction preserves CRLF and UTF8 raw bytes")
d = diff.build("", "a\n", "@@ -0,0 +1 @@\n+a\n")
check(diff.revert(d, 1) == "", "revert sole addition to zero bytes")
check(not pcall(diff.revert, d, 0) and not pcall(diff.revert, d, 2), "invalid hunk index refused")
d.invalidated = true
check(not pcall(diff.revert, d, 1), "invalidated hunk cannot be reconstructed for action")
print(checks .. " pure diff checks passed.")
